//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("UFSoft.UBF.Exceptions", ClrNamespace="UFSoft.UBF.Exceptions")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.datacontract.org/2004/07/UFSoft.UBF.Exceptions", ClrNamespace="UFSoft.UBF.Exceptions1")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.UFIDA.org/EntityData", ClrNamespace="www.ufida.org.EntityData")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("UFSoft.UBF.Util.Data", ClrNamespace="UFSoft.UBF.Util.Data")]

namespace System.Data
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRowState", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum DataRowState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detached = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 16,
    }
}
namespace UFSoft.UBF
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    public partial class ExceptionBase : System.Exception
    {
        
        public ExceptionBase(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionBase.FormatState", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
        public enum FormatState : uint
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            None = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formatting = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formatted = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class UnknownException : UFSoft.UBF.ExceptionBase
    {
        
        public UnknownException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UFSoft.UBF.ErrorDescriptor errDescriptorField;
        
        private string errorTypeField;
        
        private UFSoft.UBF.ErrorMessage[] innerMessagesField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UFSoft.UBF.ErrorDescriptor errDescriptor
        {
            get
            {
                return this.errDescriptorField;
            }
            set
            {
                this.errDescriptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string errorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ErrorMessage[] innerMessages
        {
            get
            {
                return this.innerMessagesField;
            }
            set
            {
                this.innerMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDescriptor", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string categoryField;
        
        private string erroridField;
        
        private UFSoft.UBF.ErrorLevel levelField;
        
        private string ownerField;
        
        private System.DateTime timeStampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string errorid
        {
            get
            {
                return this.erroridField;
            }
            set
            {
                this.erroridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ErrorLevel level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorLevel", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public enum ErrorLevel : short
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warn = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal = 4,
    }
}
namespace UFSoft.UBF.Service
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ServiceLostException : UFSoft.UBF.ExceptionBase
    {
        
        public ServiceLostException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ServiceException : UFSoft.UBF.ExceptionBase
    {
        
        public ServiceException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceExceptionDetail", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    public partial class ServiceExceptionDetail : System.ServiceModel.ExceptionDetail, System.Runtime.Serialization.IExtensibleDataObject
    {
        public ServiceExceptionDetail(Exception ex)
            : base(ex)
        { }

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.ExceptionBase ExceptionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ExceptionBase Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Business
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    public partial class BusinessException : UFSoft.UBF.ExceptionBase
    {
        
        public BusinessException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class AttrsContainerException : UFSoft.UBF.Business.BusinessException
    {
        
        public AttrsContainerException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class AttributeInValidException : UFSoft.UBF.Business.BusinessException
    {
        
        public AttributeInValidException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class EntityNotExistException : UFSoft.UBF.Business.BusinessException
    {
        
        public EntityNotExistException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
}
namespace UFSoft.UBF.Exceptions
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageBase", Namespace="UFSoft.UBF.Exceptions")]
    public partial class MessageBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string attributeMetadataIDField;
        
        private string attributeNameField;
        
        private string entityFullNameField;
        
        private long entityIDField;
        
        private string entityMetadataIDField;
        
        private short errorLevelField;
        
        private UFSoft.UBF.Exceptions1.MessageBaseFormatState formatedField;
        
        private UFSoft.UBF.Exceptions.MessageBase[] innerMessagesField;
        
        private bool isValidEntityIDField;
        
        private string localMessageField;
        
        private string orginalEntityFullNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attributeMetadataID
        {
            get
            {
                return this.attributeMetadataIDField;
            }
            set
            {
                this.attributeMetadataIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entityFullName
        {
            get
            {
                return this.entityFullNameField;
            }
            set
            {
                this.entityFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long entityID
        {
            get
            {
                return this.entityIDField;
            }
            set
            {
                this.entityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entityMetadataID
        {
            get
            {
                return this.entityMetadataIDField;
            }
            set
            {
                this.entityMetadataIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short errorLevel
        {
            get
            {
                return this.errorLevelField;
            }
            set
            {
                this.errorLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Exceptions1.MessageBaseFormatState formated
        {
            get
            {
                return this.formatedField;
            }
            set
            {
                this.formatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Exceptions.MessageBase[] innerMessages
        {
            get
            {
                return this.innerMessagesField;
            }
            set
            {
                this.innerMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isValidEntityID
        {
            get
            {
                return this.isValidEntityIDField;
            }
            set
            {
                this.isValidEntityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localMessage
        {
            get
            {
                return this.localMessageField;
            }
            set
            {
                this.localMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orginalEntityFullName
        {
            get
            {
                return this.orginalEntityFullNameField;
            }
            set
            {
                this.orginalEntityFullNameField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Exceptions1
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageBase.FormatState", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Exceptions")]
    public enum MessageBaseFormatState : uint
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formatting = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formatted = 2,
    }
}
namespace www.ufida.org.EntityData
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UFIDA.U9.Cust.CommonAPISV.DocDTOData", Namespace="http://www.UFIDA.org/EntityData", IsReference=true)]
    public partial class UFIDAU9CustCommonAPISVDocDTOData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {
        
        private www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData m_descFlexFieldField;
        
        private www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData[] m_docLineDTOsField;
        
        private long m_lgField;
        
        private long[] m_lgsField;
        
        private decimal m_rtnDecimalField;
        
        private long m_rtnLgField;
        
        private long[] m_rtnLgsField;
        
        private string m_rtnStrField;
        
        private string[] m_rtnStrsField;
        
        private bool m_rtnboolField;
        
        private string m_strField;
        
        private string[] m_strsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData m_descFlexField
        {
            get
            {
                return this.m_descFlexFieldField;
            }
            set
            {
                this.m_descFlexFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData[] m_docLineDTOs
        {
            get
            {
                return this.m_docLineDTOsField;
            }
            set
            {
                this.m_docLineDTOsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_lg
        {
            get
            {
                return this.m_lgField;
            }
            set
            {
                this.m_lgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] m_lgs
        {
            get
            {
                return this.m_lgsField;
            }
            set
            {
                this.m_lgsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal m_rtnDecimal
        {
            get
            {
                return this.m_rtnDecimalField;
            }
            set
            {
                this.m_rtnDecimalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_rtnLg
        {
            get
            {
                return this.m_rtnLgField;
            }
            set
            {
                this.m_rtnLgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] m_rtnLgs
        {
            get
            {
                return this.m_rtnLgsField;
            }
            set
            {
                this.m_rtnLgsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_rtnStr
        {
            get
            {
                return this.m_rtnStrField;
            }
            set
            {
                this.m_rtnStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] m_rtnStrs
        {
            get
            {
                return this.m_rtnStrsField;
            }
            set
            {
                this.m_rtnStrsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_rtnbool
        {
            get
            {
                return this.m_rtnboolField;
            }
            set
            {
                this.m_rtnboolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_str
        {
            get
            {
                return this.m_strField;
            }
            set
            {
                this.m_strField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] m_strs
        {
            get
            {
                return this.m_strsField;
            }
            set
            {
                this.m_strsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UFSoft.UBF.Business.DataTransObjectBase", Namespace="http://www.UFIDA.org/EntityData", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData))]
    public partial class UFSoftUBFBusinessDataTransObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UFSoft.UBF.PL.Engine.ObjectState sysStateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.PL.Engine.ObjectState sysState
        {
            get
            {
                return this.sysStateField;
            }
            set
            {
                this.sysStateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UFIDA.U9.Base.FlexField.DescFlexField.DescFlexSegmentsData", Namespace="http://www.UFIDA.org/EntityData", IsReference=true)]
    public partial class UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {
        
        private string CombineNameField;
        
        private UFSoft.UBF.Util.Data.MultiLangDataDict Multi_CombineNameField;
        
        private string m_contextValueField;
        
        private string m_privateDescSeg1Field;
        
        private string m_privateDescSeg10Field;
        
        private string m_privateDescSeg11Field;
        
        private string m_privateDescSeg12Field;
        
        private string m_privateDescSeg13Field;
        
        private string m_privateDescSeg14Field;
        
        private string m_privateDescSeg15Field;
        
        private string m_privateDescSeg16Field;
        
        private string m_privateDescSeg17Field;
        
        private string m_privateDescSeg18Field;
        
        private string m_privateDescSeg19Field;
        
        private string m_privateDescSeg2Field;
        
        private string m_privateDescSeg20Field;
        
        private string m_privateDescSeg21Field;
        
        private string m_privateDescSeg22Field;
        
        private string m_privateDescSeg23Field;
        
        private string m_privateDescSeg24Field;
        
        private string m_privateDescSeg25Field;
        
        private string m_privateDescSeg26Field;
        
        private string m_privateDescSeg27Field;
        
        private string m_privateDescSeg28Field;
        
        private string m_privateDescSeg29Field;
        
        private string m_privateDescSeg3Field;
        
        private string m_privateDescSeg30Field;
        
        private string m_privateDescSeg4Field;
        
        private string m_privateDescSeg5Field;
        
        private string m_privateDescSeg6Field;
        
        private string m_privateDescSeg7Field;
        
        private string m_privateDescSeg8Field;
        
        private string m_privateDescSeg9Field;
        
        private string m_pubDescSeg1Field;
        
        private string m_pubDescSeg10Field;
        
        private string m_pubDescSeg11Field;
        
        private string m_pubDescSeg12Field;
        
        private string m_pubDescSeg13Field;
        
        private string m_pubDescSeg14Field;
        
        private string m_pubDescSeg15Field;
        
        private string m_pubDescSeg16Field;
        
        private string m_pubDescSeg17Field;
        
        private string m_pubDescSeg18Field;
        
        private string m_pubDescSeg19Field;
        
        private string m_pubDescSeg2Field;
        
        private string m_pubDescSeg20Field;
        
        private string m_pubDescSeg21Field;
        
        private string m_pubDescSeg22Field;
        
        private string m_pubDescSeg23Field;
        
        private string m_pubDescSeg24Field;
        
        private string m_pubDescSeg25Field;
        
        private string m_pubDescSeg26Field;
        
        private string m_pubDescSeg27Field;
        
        private string m_pubDescSeg28Field;
        
        private string m_pubDescSeg29Field;
        
        private string m_pubDescSeg3Field;
        
        private string m_pubDescSeg30Field;
        
        private string m_pubDescSeg31Field;
        
        private string m_pubDescSeg32Field;
        
        private string m_pubDescSeg33Field;
        
        private string m_pubDescSeg34Field;
        
        private string m_pubDescSeg35Field;
        
        private string m_pubDescSeg36Field;
        
        private string m_pubDescSeg37Field;
        
        private string m_pubDescSeg38Field;
        
        private string m_pubDescSeg39Field;
        
        private string m_pubDescSeg4Field;
        
        private string m_pubDescSeg40Field;
        
        private string m_pubDescSeg41Field;
        
        private string m_pubDescSeg42Field;
        
        private string m_pubDescSeg43Field;
        
        private string m_pubDescSeg44Field;
        
        private string m_pubDescSeg45Field;
        
        private string m_pubDescSeg46Field;
        
        private string m_pubDescSeg47Field;
        
        private string m_pubDescSeg48Field;
        
        private string m_pubDescSeg49Field;
        
        private string m_pubDescSeg5Field;
        
        private string m_pubDescSeg50Field;
        
        private string m_pubDescSeg6Field;
        
        private string m_pubDescSeg7Field;
        
        private string m_pubDescSeg8Field;
        
        private string m_pubDescSeg9Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CombineName
        {
            get
            {
                return this.CombineNameField;
            }
            set
            {
                this.CombineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Util.Data.MultiLangDataDict Multi_CombineName
        {
            get
            {
                return this.Multi_CombineNameField;
            }
            set
            {
                this.Multi_CombineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_contextValue
        {
            get
            {
                return this.m_contextValueField;
            }
            set
            {
                this.m_contextValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg1
        {
            get
            {
                return this.m_privateDescSeg1Field;
            }
            set
            {
                this.m_privateDescSeg1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg10
        {
            get
            {
                return this.m_privateDescSeg10Field;
            }
            set
            {
                this.m_privateDescSeg10Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg11
        {
            get
            {
                return this.m_privateDescSeg11Field;
            }
            set
            {
                this.m_privateDescSeg11Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg12
        {
            get
            {
                return this.m_privateDescSeg12Field;
            }
            set
            {
                this.m_privateDescSeg12Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg13
        {
            get
            {
                return this.m_privateDescSeg13Field;
            }
            set
            {
                this.m_privateDescSeg13Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg14
        {
            get
            {
                return this.m_privateDescSeg14Field;
            }
            set
            {
                this.m_privateDescSeg14Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg15
        {
            get
            {
                return this.m_privateDescSeg15Field;
            }
            set
            {
                this.m_privateDescSeg15Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg16
        {
            get
            {
                return this.m_privateDescSeg16Field;
            }
            set
            {
                this.m_privateDescSeg16Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg17
        {
            get
            {
                return this.m_privateDescSeg17Field;
            }
            set
            {
                this.m_privateDescSeg17Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg18
        {
            get
            {
                return this.m_privateDescSeg18Field;
            }
            set
            {
                this.m_privateDescSeg18Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg19
        {
            get
            {
                return this.m_privateDescSeg19Field;
            }
            set
            {
                this.m_privateDescSeg19Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg2
        {
            get
            {
                return this.m_privateDescSeg2Field;
            }
            set
            {
                this.m_privateDescSeg2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg20
        {
            get
            {
                return this.m_privateDescSeg20Field;
            }
            set
            {
                this.m_privateDescSeg20Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg21
        {
            get
            {
                return this.m_privateDescSeg21Field;
            }
            set
            {
                this.m_privateDescSeg21Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg22
        {
            get
            {
                return this.m_privateDescSeg22Field;
            }
            set
            {
                this.m_privateDescSeg22Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg23
        {
            get
            {
                return this.m_privateDescSeg23Field;
            }
            set
            {
                this.m_privateDescSeg23Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg24
        {
            get
            {
                return this.m_privateDescSeg24Field;
            }
            set
            {
                this.m_privateDescSeg24Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg25
        {
            get
            {
                return this.m_privateDescSeg25Field;
            }
            set
            {
                this.m_privateDescSeg25Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg26
        {
            get
            {
                return this.m_privateDescSeg26Field;
            }
            set
            {
                this.m_privateDescSeg26Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg27
        {
            get
            {
                return this.m_privateDescSeg27Field;
            }
            set
            {
                this.m_privateDescSeg27Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg28
        {
            get
            {
                return this.m_privateDescSeg28Field;
            }
            set
            {
                this.m_privateDescSeg28Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg29
        {
            get
            {
                return this.m_privateDescSeg29Field;
            }
            set
            {
                this.m_privateDescSeg29Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg3
        {
            get
            {
                return this.m_privateDescSeg3Field;
            }
            set
            {
                this.m_privateDescSeg3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg30
        {
            get
            {
                return this.m_privateDescSeg30Field;
            }
            set
            {
                this.m_privateDescSeg30Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg4
        {
            get
            {
                return this.m_privateDescSeg4Field;
            }
            set
            {
                this.m_privateDescSeg4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg5
        {
            get
            {
                return this.m_privateDescSeg5Field;
            }
            set
            {
                this.m_privateDescSeg5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg6
        {
            get
            {
                return this.m_privateDescSeg6Field;
            }
            set
            {
                this.m_privateDescSeg6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg7
        {
            get
            {
                return this.m_privateDescSeg7Field;
            }
            set
            {
                this.m_privateDescSeg7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg8
        {
            get
            {
                return this.m_privateDescSeg8Field;
            }
            set
            {
                this.m_privateDescSeg8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_privateDescSeg9
        {
            get
            {
                return this.m_privateDescSeg9Field;
            }
            set
            {
                this.m_privateDescSeg9Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg1
        {
            get
            {
                return this.m_pubDescSeg1Field;
            }
            set
            {
                this.m_pubDescSeg1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg10
        {
            get
            {
                return this.m_pubDescSeg10Field;
            }
            set
            {
                this.m_pubDescSeg10Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg11
        {
            get
            {
                return this.m_pubDescSeg11Field;
            }
            set
            {
                this.m_pubDescSeg11Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg12
        {
            get
            {
                return this.m_pubDescSeg12Field;
            }
            set
            {
                this.m_pubDescSeg12Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg13
        {
            get
            {
                return this.m_pubDescSeg13Field;
            }
            set
            {
                this.m_pubDescSeg13Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg14
        {
            get
            {
                return this.m_pubDescSeg14Field;
            }
            set
            {
                this.m_pubDescSeg14Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg15
        {
            get
            {
                return this.m_pubDescSeg15Field;
            }
            set
            {
                this.m_pubDescSeg15Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg16
        {
            get
            {
                return this.m_pubDescSeg16Field;
            }
            set
            {
                this.m_pubDescSeg16Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg17
        {
            get
            {
                return this.m_pubDescSeg17Field;
            }
            set
            {
                this.m_pubDescSeg17Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg18
        {
            get
            {
                return this.m_pubDescSeg18Field;
            }
            set
            {
                this.m_pubDescSeg18Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg19
        {
            get
            {
                return this.m_pubDescSeg19Field;
            }
            set
            {
                this.m_pubDescSeg19Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg2
        {
            get
            {
                return this.m_pubDescSeg2Field;
            }
            set
            {
                this.m_pubDescSeg2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg20
        {
            get
            {
                return this.m_pubDescSeg20Field;
            }
            set
            {
                this.m_pubDescSeg20Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg21
        {
            get
            {
                return this.m_pubDescSeg21Field;
            }
            set
            {
                this.m_pubDescSeg21Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg22
        {
            get
            {
                return this.m_pubDescSeg22Field;
            }
            set
            {
                this.m_pubDescSeg22Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg23
        {
            get
            {
                return this.m_pubDescSeg23Field;
            }
            set
            {
                this.m_pubDescSeg23Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg24
        {
            get
            {
                return this.m_pubDescSeg24Field;
            }
            set
            {
                this.m_pubDescSeg24Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg25
        {
            get
            {
                return this.m_pubDescSeg25Field;
            }
            set
            {
                this.m_pubDescSeg25Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg26
        {
            get
            {
                return this.m_pubDescSeg26Field;
            }
            set
            {
                this.m_pubDescSeg26Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg27
        {
            get
            {
                return this.m_pubDescSeg27Field;
            }
            set
            {
                this.m_pubDescSeg27Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg28
        {
            get
            {
                return this.m_pubDescSeg28Field;
            }
            set
            {
                this.m_pubDescSeg28Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg29
        {
            get
            {
                return this.m_pubDescSeg29Field;
            }
            set
            {
                this.m_pubDescSeg29Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg3
        {
            get
            {
                return this.m_pubDescSeg3Field;
            }
            set
            {
                this.m_pubDescSeg3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg30
        {
            get
            {
                return this.m_pubDescSeg30Field;
            }
            set
            {
                this.m_pubDescSeg30Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg31
        {
            get
            {
                return this.m_pubDescSeg31Field;
            }
            set
            {
                this.m_pubDescSeg31Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg32
        {
            get
            {
                return this.m_pubDescSeg32Field;
            }
            set
            {
                this.m_pubDescSeg32Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg33
        {
            get
            {
                return this.m_pubDescSeg33Field;
            }
            set
            {
                this.m_pubDescSeg33Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg34
        {
            get
            {
                return this.m_pubDescSeg34Field;
            }
            set
            {
                this.m_pubDescSeg34Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg35
        {
            get
            {
                return this.m_pubDescSeg35Field;
            }
            set
            {
                this.m_pubDescSeg35Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg36
        {
            get
            {
                return this.m_pubDescSeg36Field;
            }
            set
            {
                this.m_pubDescSeg36Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg37
        {
            get
            {
                return this.m_pubDescSeg37Field;
            }
            set
            {
                this.m_pubDescSeg37Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg38
        {
            get
            {
                return this.m_pubDescSeg38Field;
            }
            set
            {
                this.m_pubDescSeg38Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg39
        {
            get
            {
                return this.m_pubDescSeg39Field;
            }
            set
            {
                this.m_pubDescSeg39Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg4
        {
            get
            {
                return this.m_pubDescSeg4Field;
            }
            set
            {
                this.m_pubDescSeg4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg40
        {
            get
            {
                return this.m_pubDescSeg40Field;
            }
            set
            {
                this.m_pubDescSeg40Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg41
        {
            get
            {
                return this.m_pubDescSeg41Field;
            }
            set
            {
                this.m_pubDescSeg41Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg42
        {
            get
            {
                return this.m_pubDescSeg42Field;
            }
            set
            {
                this.m_pubDescSeg42Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg43
        {
            get
            {
                return this.m_pubDescSeg43Field;
            }
            set
            {
                this.m_pubDescSeg43Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg44
        {
            get
            {
                return this.m_pubDescSeg44Field;
            }
            set
            {
                this.m_pubDescSeg44Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg45
        {
            get
            {
                return this.m_pubDescSeg45Field;
            }
            set
            {
                this.m_pubDescSeg45Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg46
        {
            get
            {
                return this.m_pubDescSeg46Field;
            }
            set
            {
                this.m_pubDescSeg46Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg47
        {
            get
            {
                return this.m_pubDescSeg47Field;
            }
            set
            {
                this.m_pubDescSeg47Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg48
        {
            get
            {
                return this.m_pubDescSeg48Field;
            }
            set
            {
                this.m_pubDescSeg48Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg49
        {
            get
            {
                return this.m_pubDescSeg49Field;
            }
            set
            {
                this.m_pubDescSeg49Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg5
        {
            get
            {
                return this.m_pubDescSeg5Field;
            }
            set
            {
                this.m_pubDescSeg5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg50
        {
            get
            {
                return this.m_pubDescSeg50Field;
            }
            set
            {
                this.m_pubDescSeg50Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg6
        {
            get
            {
                return this.m_pubDescSeg6Field;
            }
            set
            {
                this.m_pubDescSeg6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg7
        {
            get
            {
                return this.m_pubDescSeg7Field;
            }
            set
            {
                this.m_pubDescSeg7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg8
        {
            get
            {
                return this.m_pubDescSeg8Field;
            }
            set
            {
                this.m_pubDescSeg8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_pubDescSeg9
        {
            get
            {
                return this.m_pubDescSeg9Field;
            }
            set
            {
                this.m_pubDescSeg9Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UFIDA.U9.Cust.CommonAPISV.DocLineDTOData", Namespace="http://www.UFIDA.org/EntityData", IsReference=true)]
    public partial class UFIDAU9CustCommonAPISVDocLineDTOData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {
        
        private www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData m_descFlexFieldField;
        
        private www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData m_docDTOField;
        
        private int m_docLineNoField;
        
        private www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData[] m_docSubLineDTOsField;
        
        private long m_lgField;
        
        private long[] m_lgsField;
        
        private string m_strField;
        
        private string[] m_strsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData m_descFlexField
        {
            get
            {
                return this.m_descFlexFieldField;
            }
            set
            {
                this.m_descFlexFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData m_docDTO
        {
            get
            {
                return this.m_docDTOField;
            }
            set
            {
                this.m_docDTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_docLineNo
        {
            get
            {
                return this.m_docLineNoField;
            }
            set
            {
                this.m_docLineNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData[] m_docSubLineDTOs
        {
            get
            {
                return this.m_docSubLineDTOsField;
            }
            set
            {
                this.m_docSubLineDTOsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_lg
        {
            get
            {
                return this.m_lgField;
            }
            set
            {
                this.m_lgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] m_lgs
        {
            get
            {
                return this.m_lgsField;
            }
            set
            {
                this.m_lgsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_str
        {
            get
            {
                return this.m_strField;
            }
            set
            {
                this.m_strField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] m_strs
        {
            get
            {
                return this.m_strsField;
            }
            set
            {
                this.m_strsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UFIDA.U9.Cust.CommonAPISV.DocSubLineDTOData", Namespace="http://www.UFIDA.org/EntityData", IsReference=true)]
    public partial class UFIDAU9CustCommonAPISVDocSubLineDTOData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {
        
        private www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData m_descFlexFieldField;
        
        private www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData m_docLineDTOField;
        
        private int m_docSubLineNoField;
        
        private long m_lgField;
        
        private long[] m_lgsField;
        
        private string m_strField;
        
        private string[] m_strsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData m_descFlexField
        {
            get
            {
                return this.m_descFlexFieldField;
            }
            set
            {
                this.m_descFlexFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData m_docLineDTO
        {
            get
            {
                return this.m_docLineDTOField;
            }
            set
            {
                this.m_docLineDTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_docSubLineNo
        {
            get
            {
                return this.m_docSubLineNoField;
            }
            set
            {
                this.m_docSubLineNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_lg
        {
            get
            {
                return this.m_lgField;
            }
            set
            {
                this.m_lgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] m_lgs
        {
            get
            {
                return this.m_lgsField;
            }
            set
            {
                this.m_lgsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_str
        {
            get
            {
                return this.m_strField;
            }
            set
            {
                this.m_strField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] m_strs
        {
            get
            {
                return this.m_strsField;
            }
            set
            {
                this.m_strsField = value;
            }
        }
    }
}
namespace UFSoft.UBF.PL.Engine
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.PL.Engine")]
    public enum ObjectState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotExist = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inserted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updated = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operating = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NeedLoad = 10,
    }
}
namespace UFSoft.UBF.Util.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiLangDataDict", Namespace="UFSoft.UBF.Util.Data")]
    public partial class MultiLangDataDict : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UFSoft.UBF.Util.Data.MultiLangData[] _langsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Util.Data.MultiLangData[] _langs
        {
            get
            {
                return this._langsField;
            }
            set
            {
                this._langsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiLangData", Namespace="UFSoft.UBF.Util.Data")]
    public partial class MultiLangData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LangTypeField;
        
        private string LangValueField;
        
        private System.Data.DataRowState StateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LangType
        {
            get
            {
                return this.LangTypeField;
            }
            set
            {
                this.LangTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LangValue
        {
            get
            {
                return this.LangValueField;
            }
            set
            {
                this.LangValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataRowState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Util.Context
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationContext", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ApplicationContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<object, object> nameValueHasField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<object, object> nameValueHas
        {
            get
            {
                return this.nameValueHasField;
            }
            set
            {
                this.nameValueHasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformContext", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBase[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBaseFormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(long[]))]
    public partial class PlatformContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object ctxField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object ctx
        {
            get
            {
                return this.ctxField;
            }
            set
            {
                this.ctxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThreadContext", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ThreadContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<object, object> nameValueHasField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<object, object> nameValueHas
        {
            get
            {
                return this.nameValueHasField;
            }
            set
            {
                this.nameValueHasField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name="UFIDA.U9.Cust.CommonAPISV.ICommonAPISv", Namespace="http://www.UFIDA.org", ConfigurationName="UFIDAU9CustCommonAPISVICommonAPISv")]
public interface UFIDAU9CustCommonAPISVICommonAPISv
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/Do", ReplyAction="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/DoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceLostException), Action="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/DoServiceLostExceptio" +
        "nFault", Name="ServiceLostException", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceException), Action="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/DoServiceExceptionFau" +
        "lt", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail), Action="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/DoServiceExceptionDet" +
        "ailFault", Name="ServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.ExceptionBase), Action="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/DoExceptionBaseFault", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://www.UFIDA.org/UFIDA.U9.Cust.CommonAPISV.ICommonAPISv/DoExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBase[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocLineDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocSubLineDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.PlatformContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBaseFormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData[] Do(out UFSoft.UBF.Exceptions.MessageBase[] outMessages, object context, string commandType, string[] strs, string str, long lg, long[] lgs, www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData[] docDTOs);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface UFIDAU9CustCommonAPISVICommonAPISvChannel : UFIDAU9CustCommonAPISVICommonAPISv, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class UFIDAU9CustCommonAPISVICommonAPISvClient : System.ServiceModel.ClientBase<UFIDAU9CustCommonAPISVICommonAPISv>, UFIDAU9CustCommonAPISVICommonAPISv
{
    
    public UFIDAU9CustCommonAPISVICommonAPISvClient()
    {
    }
    
    public UFIDAU9CustCommonAPISVICommonAPISvClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UFIDAU9CustCommonAPISVICommonAPISvClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UFIDAU9CustCommonAPISVICommonAPISvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UFIDAU9CustCommonAPISVICommonAPISvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData[] Do(out UFSoft.UBF.Exceptions.MessageBase[] outMessages, object context, string commandType, string[] strs, string str, long lg, long[] lgs, www.ufida.org.EntityData.UFIDAU9CustCommonAPISVDocDTOData[] docDTOs)
    {
        return base.Channel.Do(out outMessages, context, commandType, strs, str, lg, lgs, docDTOs);
    }
}
